### ISSUE TITLE
How to set up MHub using MacOS system?

### ISSUE THREAD

**Issue by Wwwendyy** [AIM-Harvard/mhub#15]
When I tried to install Docker using MacOS systems, it always showes errors again and again. It showed "You are using macOS 11.3.1. This application requires macOS 12.0 or later"

**Comment by LennyN95** [comment]
Hey thank you for your interest. This repository is an outdated version, please find the latest MHub platform at https://mhub.ai/. There you will find all our models and links to our documentation and tutorials.

The simplest way to install Docker on a Mac is by installing Docker Desktop. Make sure your system is on the latest (or a supported) version. Also be careful choosing the right system architecture (e.g., install Docker Desktop for Intel if you have a MacBook with an i5 or i7 processor and Docker Desktop for Apple Silicon if you have a newer MacBook with an Apple M1 (or later) processor).
